package app

import (
	"fmt"
	"io"
	"strings"
)

// configSubcommands lists the public config-domain routes, in help order.
var configSubcommands = []string{"edit", "render", "apply"}

// configRenderArtifacts lists the two generated artifacts `config render` can
// print, in help order.
//
// There are two because projmux generates two different tmux configs, not two
// projections of one. The standalone snippet is what an operator sources from
// their own `~/.tmux.conf`; the app config is the file the app-owned projmux
// tmux server runs from, and it additionally carries the default shell and the
// app-only bindings. `tmux print-config` and `tmux print-app-config` have always
// been two routes over two payloads, so the public spelling names the artifact
// rather than pretending one of them is the default.
var configRenderArtifacts = []string{"standalone", "app"}

// configCommand owns the public `config` domain: the generated-tmux-config
// operations an operator is actually meant to type.
//
// Every route here is a parity alias. Each forwards raw argv to the AI or
// tmux handler that already owns the behavior, so stdout, stderr, the exit code,
// and the side effects are byte-identical to the current spelling:
//
//	projmux config render standalone  ==  projmux internal tmux print-config
//	projmux config render app         ==  projmux internal tmux print-app-config
//	projmux config apply              ==  projmux internal tmux apply
//	projmux config edit               ==  projmux ai settings
//
// The artifact is a positional token, not a flag. That is what keeps this node
// the same dumb forwarder every other namespace in the tree is: dispatch reads
// leading tokens only and hands the entire remainder through untouched, so
// `--bin` and friends stay the leaf parser's business and no node in the command
// tree turns flag parsing on. It also matches the repo's verb-then-kind grammar
// -- `get panes`, `delete pane`, `restore snapshot` -- rather than inventing a
// boolean that selects between two nouns.
//
// A bare `config render` is a usage error listing the artifacts, which is what
// every other kind-taking namespace does (`get`, `create`, `delete`, `describe`,
// `restore`, `runtime`, `agent` all answer a bare invocation the same way and
// exit 2). Defaulting to one artifact would make the other one look like an
// afterthought and would silently pick a payload on the user's behalf.
//
// `apply` takes no artifact because there is only one: it writes the app tmux
// config and reloads the live server. The standalone snippet's write-and-include
// counterpart is `tmux install`, which stays hidden-only along with
// `install-app`. Those two are installer plumbing, not something a user drives
// by hand, so they get no public spelling and the summaries here are careful not
// to imply otherwise.
//
// The hidden spellings are not deprecated and emit no warning. A tmux server
// that is already running holds config generated by a previously installed
// binary and keeps invoking them, while `make install` calls the canonical
// `$(INSTALL_BIN) config apply` route.
type configCommand struct {
	tmux rawArgvCommand
	ai   rawArgvCommand
}

func newConfigCommand() *configCommand {
	return &configCommand{}
}

// Run dispatches one `config <subcommand>` invocation.
func (c *configCommand) Run(args []string, stdout, stderr io.Writer) error {
	if len(args) == 0 {
		return usageError(fmt.Sprintf("config requires a subcommand: %s", strings.Join(configSubcommands, ", ")))
	}
	rest := args[1:]
	switch args[0] {
	case "edit":
		return forwardRawArgv(c.ai, "config edit", "ai", []string{"settings"}, rest, stdout, stderr)
	case "render":
		return c.runRender(rest, stdout, stderr)
	case "apply":
		return forwardRawArgv(c.tmux, "config apply", "tmux", []string{"apply"}, rest, stdout, stderr)
	default:
		return usageError(fmt.Sprintf("config %s is not available; this release implements: %s",
			args[0], strings.Join(configSubcommands, ", ")))
	}
}

// runRender routes one `config render <artifact>` invocation onto the tmux
// printer that owns that artifact.
func (c *configCommand) runRender(args []string, stdout, stderr io.Writer) error {
	if len(args) == 0 {
		return usageError(fmt.Sprintf("config render requires an artifact: %s",
			strings.Join(configRenderArtifacts, ", ")))
	}
	switch args[0] {
	case "standalone":
		return forwardRawArgv(c.tmux, "config render standalone", "tmux", []string{"print-config"}, args[1:], stdout, stderr)
	case "app":
		return forwardRawArgv(c.tmux, "config render app", "tmux", []string{"print-app-config"}, args[1:], stdout, stderr)
	default:
		return usageError(fmt.Sprintf("config render %s is not available; this release implements: %s",
			args[0], strings.Join(configRenderArtifacts, ", ")))
	}
}
