package app

import (
	"fmt"
	"strings"

	intpsmux "github.com/crevissepartners/projmux/internal/integrations/psmux"
)

func psmuxAppConfig(binaryPath string) (string, error) {
	statusGit, err := intpsmux.ProjmuxCommand(binaryPath, "status", "git", "#{pane_current_path}").PowerShell()
	if err != nil {
		return "", fmt.Errorf("render psmux status git command: %w", err)
	}
	lines := []string{
		"# Generated by projmux. Used by native Windows `projmux.exe shell` with psmux.",
		"# Phase 3A0-5 intentionally omits pane-scoped metadata, session-state replay, popups, and rich hooks.",
		"set -g @projmux_app 1",
		"set -g mouse on",
		"set -g history-limit 10000",
		"set -g status on",
		"set -g status-position bottom",
		"set -g status-interval 5",
		"set -g status-left " + psmuxConfigQuote(" #{session_name} "),
		"set -g status-right " + psmuxConfigQuote("#("+statusGit+")  %Y-%m-%d %H:%M "),
		"set -g window-status-separator \" \"",
		"set -g allow-rename off",
		"set -g automatic-rename on",
		"bind-key -n C-n new-window -c " + psmuxConfigQuote("#{pane_current_path}"),
	}
	return strings.Join(lines, "\n") + "\n", nil
}

func psmuxConfigQuote(value string) string {
	return "\"" + strings.ReplaceAll(value, "\"", "\\\"") + "\""
}
