package app

import (
	"bytes"
	"context"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	intfzf "github.com/crevissepartners/projmux/internal/ui/fzf"
)

func TestShellWritesAppConfigAndRunsIsolatedTmux(t *testing.T) {
	t.Setenv("TMUX", "/tmp/default-tmux")

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/proj mux/bin/projmux", nil },
		lookupEnv: func(name string) string {
			if name == "HOME" {
				return home
			}
			if name == "XDG_CONFIG_HOME" {
				return ""
			}
			if name == "SHELL" {
				return "/bin/bash"
			}
			return os.Getenv(name)
		},
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}

	if err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	configPath := filepath.Join(home, ".config", "projmux", "tmux.conf")
	content, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatal(err)
	}
	config := string(content)
	for _, want := range []string{
		"Generated by projmux. Used by `projmux shell`.",
		"set -g @projmux_app 1",
		"set -g history-limit 10000",
		"set -g set-clipboard on",
		"set -g default-shell \"/bin/bash\"",
		"set -ga update-environment \"WSL_DISTRO_NAME\"",
		"set -g pane-border-status top",
		"set -s user-keys[7] \"\\033[9008u\"",
		"bind-key -n C-n new-window -c \"#{pane_current_path}\"",
		"bind-key -n M-r command-prompt",
		"bind-key -n User8 previous-window",
		"bind-key -n User9 next-window",
		"bind-key -n User10 command-prompt",
		"bind-key -n User11 command-prompt",
		"set -g status-left-length 20",
		"set -g status-left \"#[range=user|session]#[bold,fg=colour231,bg=colour90] #{s|^[^-]*-||:session_name} #[default]#[norange]\"",
		"#[bold,fg=colour231,bg=colour90] #{s|^[^-]*-||:session_name} #[default]",
		"'/tmp/proj mux/bin/projmux' tmux popup-toggle --client #{client_tty} sessionizer-sidebar",
		"set -g status 2",
		"range=user|notify",
		"range=user|usage",
		"align=left",
		"align=right",
		"set -gu status-format[2]",
	} {
		if !strings.Contains(config, want) {
			t.Fatalf("config = %q, want substring %q", config, want)
		}
	}
	if strings.Contains(config, "#[bold,fg=colour16,bg=colour45] app #[default]") {
		t.Fatalf("config = %q, did not expect duplicate app status badge", config)
	}
	for _, banned := range []string{
		"set -g status 3",
		"set -g status-format[2] \"",
	} {
		if strings.Contains(config, banned) {
			t.Fatalf("config = %q, did not expect substring %q", config, banned)
		}
	}

	wantArgs := []string{"-L", "projmux", "-f", configPath, "new-session", "-A", "-s", "home", "-c", home}
	if recorder.name != "tmux" || !reflect.DeepEqual(recorder.args, wantArgs) {
		t.Fatalf("command = %s %#v, want tmux %#v", recorder.name, recorder.args, wantArgs)
	}
	for _, env := range recorder.env {
		if strings.HasPrefix(env, "TMUX=") {
			t.Fatalf("runner env contains TMUX: %#v", recorder.env)
		}
	}
}

func TestShellAppConfigFallsBackToPortableShell(t *testing.T) {
	t.Parallel()

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv: func(name string) string {
			if name == "HOME" {
				return home
			}
			return ""
		},
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}

	if err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	configPath := filepath.Join(home, ".config", "projmux", "tmux.conf")
	content, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(content), "set -g default-shell \"/bin/sh\"") {
		t.Fatalf("config = %q, want portable fallback shell", string(content))
	}
}

func TestDefaultInteractiveShellKeepsConfiguredZsh(t *testing.T) {
	t.Parallel()

	got := defaultInteractiveShell(func(name string) string {
		if name == "SHELL" {
			return "/usr/bin/zsh"
		}
		return ""
	})
	if got != "/usr/bin/zsh" {
		t.Fatalf("defaultInteractiveShell = %q, want configured zsh", got)
	}
}

func TestShellSupportsRuntimeOverrides(t *testing.T) {
	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}
	configPath := filepath.Join(home, "custom.conf")
	args := []string{"--socket", "pmx-dev", "--session", "dev", "--config", configPath, "--bin", "/opt/projmux", "--no-install"}
	if err := cmd.Run(args, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if _, err := os.Stat(configPath); !os.IsNotExist(err) {
		t.Fatalf("config was written despite --no-install: %v", err)
	}
	wantArgs := []string{"-L", "pmx-dev", "-f", configPath, "new-session", "-A", "-s", "dev", "-c", home}
	if recorder.name != "tmux" || !reflect.DeepEqual(recorder.args, wantArgs) {
		t.Fatalf("command = %s %#v, want tmux %#v", recorder.name, recorder.args, wantArgs)
	}
}

func TestShellDefaultSessionUsesHomeProjectIdentity(t *testing.T) {
	t.Parallel()

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}

	if err := cmd.Run([]string{"--no-install"}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	wantArgs := []string{"-L", "projmux", "-f", filepath.Join(home, ".config", "projmux", "tmux.conf"), "new-session", "-A", "-s", "home", "-c", home}
	if recorder.name != "tmux" || !reflect.DeepEqual(recorder.args, wantArgs) {
		t.Fatalf("command = %s %#v, want tmux %#v", recorder.name, recorder.args, wantArgs)
	}
}

func TestShellPromptsForCachedNPMUpdateAndApplies(t *testing.T) {
	now := time.Date(2026, 5, 7, 4, 30, 0, 0, time.UTC)
	update, cacheDir := testUpdateCommand(t, now)
	update.getenv = func(name string) string {
		if name == "PROJMUX_INSTALLER" {
			return "npm"
		}
		return ""
	}
	var updateCommands []string
	update.runExternal = func(name string, args []string, stdout, stderr io.Writer) error {
		updateCommands = append(updateCommands, updateApplyCommand{Name: name, Args: args}.String())
		return nil
	}
	latest := testVersionTag(t, 1)
	writeUpdateCacheFixture(t, cacheDir, updateCache{
		Version:     1,
		CheckedAt:   now,
		TagName:     latest,
		HTMLURL:     "https://github.com/crevissepartners/projmux/releases/tag/" + latest,
		PublishedAt: now,
	})

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	var promptOptions intfzf.Options
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
		update:     update,
		updatePromptRunner: shellUpdateRunnerFunc(func(options intfzf.Options) (intfzf.Result, error) {
			promptOptions = options
			return intfzf.Result{Value: shellUpdateApply}, nil
		}),
		nativePicker: nativePickerFromFZFRunner(shellUpdateRunnerFunc(func(options intfzf.Options) (intfzf.Result, error) {
			promptOptions = options
			return intfzf.Result{Value: shellUpdateApply}, nil
		})),
	}

	var stdout bytes.Buffer
	if err := cmd.Run(nil, &stdout, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if got, want := promptOptions.UI, "shell-update"; got != want {
		t.Fatalf("prompt UI = %q, want %q", got, want)
	}
	if !strings.Contains(promptOptions.Header, latest) {
		t.Fatalf("prompt header = %q, want latest %s", promptOptions.Header, latest)
	}
	for _, want := range []string{shellUpdateApply, shellUpdateLater, shellUpdateSkip} {
		if !hasEntryValue(promptOptions.Entries, want) {
			t.Fatalf("prompt entries = %#v, want %s", promptOptions.Entries, want)
		}
	}
	wantCommands := []string{"npm update -g projmux", "projmux tmux apply"}
	if !reflect.DeepEqual(updateCommands, wantCommands) {
		t.Fatalf("update commands = %#v, want %#v", updateCommands, wantCommands)
	}
	if recorder.name != "tmux" {
		t.Fatalf("shell did not continue into tmux, command = %q", recorder.name)
	}
	if !strings.Contains(stdout.String(), ">> running: npm update -g projmux") {
		t.Fatalf("stdout = %q, want npm update command", stdout.String())
	}
}

func TestShellUpdatePromptLaterContinuesWithoutApplying(t *testing.T) {
	now := time.Date(2026, 5, 7, 4, 30, 0, 0, time.UTC)
	update, cacheDir := testUpdateCommand(t, now)
	update.getenv = func(name string) string {
		if name == "PROJMUX_INSTALLER" {
			return "npm"
		}
		return ""
	}
	update.runExternal = func(name string, args []string, stdout, stderr io.Writer) error {
		t.Fatalf("unexpected update command: %s %#v", name, args)
		return nil
	}
	writeUpdateCacheFixture(t, cacheDir, updateCache{
		Version:     1,
		CheckedAt:   now,
		TagName:     testVersionTag(t, 1),
		PublishedAt: now,
	})

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
		update:     update,
		updatePromptRunner: shellUpdateRunnerFunc(func(options intfzf.Options) (intfzf.Result, error) {
			return intfzf.Result{Value: shellUpdateLater}, nil
		}),
		nativePicker: nativePickerFromFZFRunner(shellUpdateRunnerFunc(func(options intfzf.Options) (intfzf.Result, error) {
			return intfzf.Result{Value: shellUpdateLater}, nil
		})),
	}

	if err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if recorder.name != "tmux" {
		t.Fatalf("shell did not continue into tmux, command = %q", recorder.name)
	}
}

func TestShellUpdatePromptSkipsSelectedVersion(t *testing.T) {
	now := time.Date(2026, 5, 7, 4, 30, 0, 0, time.UTC)
	update, cacheDir := testUpdateCommand(t, now)
	update.getenv = func(name string) string {
		if name == "PROJMUX_INSTALLER" {
			return "npm"
		}
		return ""
	}
	latest := testVersionTag(t, 1)
	writeUpdateCacheFixture(t, cacheDir, updateCache{
		Version:     1,
		CheckedAt:   now,
		TagName:     latest,
		PublishedAt: now,
	})

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	promptCalls := 0
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
		update:     update,
		updatePromptRunner: shellUpdateRunnerFunc(func(options intfzf.Options) (intfzf.Result, error) {
			promptCalls++
			return intfzf.Result{Value: shellUpdateSkip}, nil
		}),
		nativePicker: nativePickerFromFZFRunner(shellUpdateRunnerFunc(func(options intfzf.Options) (intfzf.Result, error) {
			promptCalls++
			return intfzf.Result{Value: shellUpdateSkip}, nil
		})),
	}

	if err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("first Run() error = %v", err)
	}
	if promptCalls != 1 {
		t.Fatalf("prompt calls after first run = %d, want 1", promptCalls)
	}
	skipPath, err := cmd.updateSkipPath()
	if err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(skipPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), latest) {
		t.Fatalf("skip state = %s, want %s", data, latest)
	}

	if err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("second Run() error = %v", err)
	}
	if promptCalls != 1 {
		t.Fatalf("prompt calls after skipped run = %d, want 1", promptCalls)
	}
}

func TestShellSkipsPromptWithoutFreshSupportedUpdate(t *testing.T) {
	now := time.Date(2026, 5, 7, 4, 30, 0, 0, time.UTC)
	update, cacheDir := testUpdateCommand(t, now)
	update.getenv = func(name string) string {
		if name == "PROJMUX_INSTALLER" {
			return "source"
		}
		return ""
	}
	writeUpdateCacheFixture(t, cacheDir, updateCache{
		Version:     1,
		CheckedAt:   now,
		TagName:     testVersionTag(t, 1),
		PublishedAt: now,
	})

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
		update:     update,
		updatePromptRunner: shellUpdateRunnerFunc(func(options intfzf.Options) (intfzf.Result, error) {
			t.Fatalf("unexpected update prompt: %#v", options)
			return intfzf.Result{}, nil
		}),
		nativePicker: nativePickerFromFZFRunner(shellUpdateRunnerFunc(func(options intfzf.Options) (intfzf.Result, error) {
			t.Fatalf("unexpected update prompt: %#v", options)
			return intfzf.Result{}, nil
		})),
	}

	if err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if recorder.name != "tmux" {
		t.Fatalf("shell did not continue into tmux, command = %q", recorder.name)
	}
}

func TestShellRejectsNestedProjmuxSocket(t *testing.T) {
	t.Setenv("TMUX", "/tmp/tmux-1000/projmux,123,0")

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  os.Getenv,
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}

	err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{})
	if err == nil {
		t.Fatal("expected nested shell error")
	}
	if !strings.Contains(err.Error(), "cannot run inside") {
		t.Fatalf("error = %v, want nested shell guard", err)
	}
	if recorder.name != "" {
		t.Fatalf("tmux command ran despite nested guard: %s %#v", recorder.name, recorder.args)
	}
	configPath := filepath.Join(home, ".config", "projmux", "tmux.conf")
	if _, err := os.Stat(configPath); !os.IsNotExist(err) {
		t.Fatalf("config was written despite nested guard: %v", err)
	}
}

func TestShellRejectsNestedCustomSocket(t *testing.T) {
	t.Setenv("TMUX", "/tmp/tmux-1000/pmx-dev,123,0")

	cmd := &shellCommand{lookupEnv: os.Getenv}
	err := cmd.Run([]string{"--socket", "pmx-dev"}, &bytes.Buffer{}, &bytes.Buffer{})
	if err == nil {
		t.Fatal("expected nested custom socket error")
	}
	if !strings.Contains(err.Error(), `"pmx-dev"`) {
		t.Fatalf("error = %v, want socket name", err)
	}
}

func TestShellRejectsInvalidUsage(t *testing.T) {
	t.Parallel()

	var stderr bytes.Buffer
	err := (&shellCommand{}).Run([]string{"extra"}, &bytes.Buffer{}, &stderr)
	if err == nil {
		t.Fatal("expected error")
	}
	if !strings.Contains(err.Error(), "shell does not accept positional arguments") {
		t.Fatalf("error = %v", err)
	}
	if !strings.Contains(stderr.String(), "Usage:") {
		t.Fatalf("stderr = %q, want usage", stderr.String())
	}
}

type recordingShellRunner struct {
	env  []string
	name string
	args []string
}

func (r *recordingShellRunner) run(_ context.Context, env []string, name string, args ...string) error {
	r.env = append([]string(nil), env...)
	r.name = name
	r.args = append([]string(nil), args...)
	return nil
}

type shellUpdateRunnerFunc func(options intfzf.Options) (intfzf.Result, error)

func (f shellUpdateRunnerFunc) Run(options intfzf.Options) (intfzf.Result, error) {
	return f(options)
}
