package app

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/crevissepartners/projmux/internal/integrations/sessionstate"
	intpickercompat "github.com/crevissepartners/projmux/internal/ui/pickercompat"
	"github.com/crevissepartners/projmux/internal/version"
)

func TestShellWritesAppConfigAndRunsIsolatedTmux(t *testing.T) {
	t.Setenv("TMUX", "/tmp/default-tmux")

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/proj mux/bin/projmux", nil },
		lookupEnv: func(name string) string {
			if name == "HOME" {
				return home
			}
			if name == "XDG_CONFIG_HOME" {
				return ""
			}
			if name == "SHELL" {
				return "/bin/bash"
			}
			return os.Getenv(name)
		},
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}

	if err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	configPath := filepath.Join(home, ".config", "projmux", "tmux.conf")
	content, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatal(err)
	}
	config := string(content)
	for _, want := range []string{
		"Generated by projmux. Used by `projmux shell`.",
		"set -g @projmux_app 1",
		"set -g history-limit 10000",
		"set -g set-clipboard on",
		"set -g default-shell \"/bin/bash\"",
		"set -ga update-environment \"WSL_DISTRO_NAME\"",
		"set -g pane-border-status top",
		"set -ga update-environment \"PROJMUX_WELCOME\"",
		"set-hook -g client-attached",
		"'/tmp/proj mux/bin/projmux' welcome --popup >/dev/null 2>&1",
		"set -s user-keys[7] \"\\033[9008u\"",
		"bind-key -n C-n new-window -c \"#{pane_current_path}\"",
		"bind-key -n M-r command-prompt",
		"bind-key -n M-S-Left previous-window",
		"bind-key -n M-S-Right next-window",
		"bind-key -n User10 command-prompt",
		"bind-key -n User11 command-prompt",
		"set -g status-left-length 20",
		"set -g status-left \"#[range=user|session]#[bold,fg=colour231,bg=colour90] #{s|^[^-]*-||:session_name} #[default]#[norange] \"",
		"#[bold,fg=colour231,bg=colour90] #{s|^[^-]*-||:session_name} #[default]",
		"#{n:window_name}",
		"#{=/7/...:window_name}",
		"'/tmp/proj mux/bin/projmux' tmux popup-toggle --client #{client_tty} sessionizer-sidebar",
		"set -g status 2",
		"range=user|settings",
		"range=user|notify",
		"range=user|usage",
		"set -g status-format[0]",
		"set -g status-format[1]",
		"align=left",
		"align=right",
		"set -gu status-format[2]",
	} {
		if !strings.Contains(config, want) {
			t.Fatalf("config = %q, want substring %q", config, want)
		}
	}
	if strings.Contains(config, "#[bold,fg=colour16,bg=colour45] app #[default]") {
		t.Fatalf("config = %q, did not expect duplicate app status badge", config)
	}
	for _, banned := range []string{
		"set -g status 3",
		"set -g status-format[2] \"",
		"range=user|sessionstate",
		// Phase 2.8 regression guard: alt-shift-arrow chords now bind to the
		// xterm-standard `M-S-Left/Right` form. Their `User8`/`User9` detour
		// is gone; if the generator regresses, popup-inside chords break in
		// Ghostty (the original bug).
		"set -s user-keys[8]",
		"set -s user-keys[9]",
		"\\033[9009u",
		"\\033[9010u",
		"bind-key -n User8",
		"bind-key -n User9",
	} {
		if strings.Contains(config, banned) {
			t.Fatalf("config = %q, did not expect substring %q", config, banned)
		}
	}

	wantArgs := []string{"-L", "projmux", "-f", configPath, "new-session", "-A", "-s", "home", "-c", home}
	if recorder.name != "tmux" || !reflect.DeepEqual(recorder.args, wantArgs) {
		t.Fatalf("command = %s %#v, want tmux %#v", recorder.name, recorder.args, wantArgs)
	}
	for _, env := range recorder.env {
		if strings.HasPrefix(env, "TMUX=") {
			t.Fatalf("runner env contains TMUX: %#v", recorder.env)
		}
	}
}

func TestShellAppConfigCanonicalizesNpmStagingBinaryPath(t *testing.T) {
	t.Setenv("TMUX", "/tmp/default-tmux")

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	stagingPath := "/home/u/.nvm/versions/node/v24.15.0/lib/node_modules/.projmux-lvpOxyM9/node_modules/@projmux/linux-x64/bin/projmux"
	cmd := &shellCommand{
		executable: func() (string, error) { return stagingPath, nil },
		lookupEnv: func(name string) string {
			if name == "HOME" {
				return home
			}
			if name == "XDG_CONFIG_HOME" {
				return ""
			}
			if name == "SHELL" {
				return "/bin/bash"
			}
			return os.Getenv(name)
		},
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}

	if err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	configPath := filepath.Join(home, ".config", "projmux", "tmux.conf")
	content, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatal(err)
	}
	config := string(content)
	want := "/home/u/.nvm/versions/node/v24.15.0/lib/node_modules/projmux/node_modules/@projmux/linux-x64/bin/projmux"
	if !strings.Contains(config, want) {
		t.Fatalf("config = %q, want substring %q", config, want)
	}
	if strings.Contains(config, ".projmux-lvpOxyM9") {
		t.Fatalf("config = %q, did not expect npm retire/staging segment %q", config, ".projmux-lvpOxyM9")
	}
}

func TestShellAppConfigFallsBackToPortableShell(t *testing.T) {
	t.Parallel()

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv: func(name string) string {
			if name == "HOME" {
				return home
			}
			return ""
		},
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}

	if err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	configPath := filepath.Join(home, ".config", "projmux", "tmux.conf")
	content, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(content), "set -g default-shell \"/bin/sh\"") {
		t.Fatalf("config = %q, want portable fallback shell", string(content))
	}
}

func TestDefaultInteractiveShellKeepsConfiguredZsh(t *testing.T) {
	t.Parallel()

	got := defaultInteractiveShell(func(name string) string {
		if name == "SHELL" {
			return "/usr/bin/zsh"
		}
		return ""
	})
	if got != "/usr/bin/zsh" {
		t.Fatalf("defaultInteractiveShell = %q, want configured zsh", got)
	}
}

func TestShellSupportsRuntimeOverrides(t *testing.T) {
	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}
	configPath := filepath.Join(home, "custom.conf")
	args := []string{"--socket", "pmx-dev", "--session", "dev", "--config", configPath, "--bin", "/opt/projmux", "--no-install"}
	if err := cmd.Run(args, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if _, err := os.Stat(configPath); !os.IsNotExist(err) {
		t.Fatalf("config was written despite --no-install: %v", err)
	}
	wantArgs := []string{"-L", "pmx-dev", "-f", configPath, "new-session", "-A", "-s", "dev", "-c", home}
	if recorder.name != "tmux" || !reflect.DeepEqual(recorder.args, wantArgs) {
		t.Fatalf("command = %s %#v, want tmux %#v", recorder.name, recorder.args, wantArgs)
	}
}

func TestShellDefaultSessionUsesProjectContextIdentity(t *testing.T) {
	t.Parallel()

	home := t.TempDir()
	project := filepath.Join(home, "source", "repos", "projmux")
	nested := filepath.Join(project, "internal", "app")
	if err := os.MkdirAll(filepath.Join(project, ".git"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(nested, 0o755); err != nil {
		t.Fatal(err)
	}
	recorder := &recordingShellRunner{}
	configPath := filepath.Join(home, ".config", "projmux", "tmux.conf")
	tmux := &scriptedShellTmuxRunner{
		errors: map[string]error{
			shellTmuxCallKey("tmux", "-L", "projmux", "-f", configPath, "has-session", "-t", "repos-projmux"): errors.New("can't find session: repos-projmux"),
		},
	}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
		tmuxRunner: tmux,
		getwd:      func() (string, error) { return nested, nil },
	}

	if err := cmd.Run([]string{"--no-install"}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	wantArgs := []string{"-L", "projmux", "-f", configPath, "new-session", "-A", "-s", "repos-projmux", "-c", project}
	if recorder.name != "tmux" || !reflect.DeepEqual(recorder.args, wantArgs) {
		t.Fatalf("command = %s %#v, want tmux %#v", recorder.name, recorder.args, wantArgs)
	}
}

func TestShellDefaultSessionUsesPROJMUXCWDProjectContext(t *testing.T) {
	t.Parallel()

	home := t.TempDir()
	envProject := filepath.Join(home, "source", "repos", "projmux")
	wdProject := filepath.Join(home, "elsewhere", "other")
	if err := os.MkdirAll(envProject, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(wdProject, ".git"), 0o755); err != nil {
		t.Fatal(err)
	}
	recorder := &recordingShellRunner{}
	configPath := filepath.Join(home, ".config", "projmux", "tmux.conf")
	tmux := &scriptedShellTmuxRunner{
		errors: map[string]error{
			shellTmuxCallKey("tmux", "-L", "projmux", "-f", configPath, "has-session", "-t", "repos-projmux"): errors.New("can't find session: repos-projmux"),
		},
	}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv: func(name string) string {
			if name == "PROJMUX_CWD" {
				return envProject
			}
			return ""
		},
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
		tmuxRunner: tmux,
		getwd:      func() (string, error) { return wdProject, nil },
	}

	if err := cmd.Run([]string{"--no-install"}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	wantArgs := []string{"-L", "projmux", "-f", configPath, "new-session", "-A", "-s", "repos-projmux", "-c", envProject}
	if recorder.name != "tmux" || !reflect.DeepEqual(recorder.args, wantArgs) {
		t.Fatalf("command = %s %#v, want tmux %#v", recorder.name, recorder.args, wantArgs)
	}
}

func TestShellDefaultSessionUsesHomeProjectIdentity(t *testing.T) {
	t.Parallel()

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}

	if err := cmd.Run([]string{"--no-install"}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	wantArgs := []string{"-L", "projmux", "-f", filepath.Join(home, ".config", "projmux", "tmux.conf"), "new-session", "-A", "-s", "home", "-c", home}
	if recorder.name != "tmux" || !reflect.DeepEqual(recorder.args, wantArgs) {
		t.Fatalf("command = %s %#v, want tmux %#v", recorder.name, recorder.args, wantArgs)
	}
}

func TestShellExplicitHomeSessionKeepsHomeTargetInsideProject(t *testing.T) {
	t.Parallel()

	home := t.TempDir()
	project := filepath.Join(home, "source", "repos", "projmux")
	if err := os.MkdirAll(filepath.Join(project, ".git"), 0o755); err != nil {
		t.Fatal(err)
	}
	store := sessionstate.NewStore(t.TempDir())
	saveShellSnapshot(t, store, "repos-projmux", project)
	foreground := &recordingShellRunner{}
	tmux := &scriptedShellTmuxRunner{}
	cmd := &shellCommand{
		executable:   func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:    func(string) string { return "" },
		homeDir:      func() (string, error) { return home, nil },
		writeFile:    os.WriteFile,
		runCommand:   foreground.run,
		tmuxRunner:   tmux,
		sessionStore: func() (sessionstate.Store, error) { return store, nil },
		getwd:        func() (string, error) { return project, nil },
		nativePicker: nativePickerFromCompatRunner(shellUpdateRunnerFunc(func(options intpickercompat.Options) (intpickercompat.Result, error) {
			t.Fatalf("startup picker should not use project snapshot for explicit home session: %#v", options)
			return intpickercompat.Result{}, nil
		})),
	}

	if err := cmd.Run([]string{"--no-install", "--session", "home"}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	if len(tmux.calls) != 0 {
		t.Fatalf("tmux restore calls = %#v, want none for explicit home target", tmux.calls)
	}
	wantArgs := []string{"-L", "projmux", "-f", filepath.Join(home, ".config", "projmux", "tmux.conf"), "new-session", "-A", "-s", "home", "-c", home}
	if foreground.name != "tmux" || !reflect.DeepEqual(foreground.args, wantArgs) {
		t.Fatalf("command = %s %#v, want tmux %#v", foreground.name, foreground.args, wantArgs)
	}
}

func TestShellUsageOmitsStartupSelectors(t *testing.T) {
	t.Parallel()

	var usage bytes.Buffer
	printShellUsage(&usage)
	for _, removed := range []string{"--saved", "--layout", "--empty"} {
		if strings.Contains(usage.String(), removed) {
			t.Fatalf("usage = %q, want no %q", usage.String(), removed)
		}
	}
}

func TestShellTmuxExecRunnerStripsNestedTmuxEnv(t *testing.T) {
	t.Parallel()

	runner := shellTmuxExecRunner{env: func() []string {
		return []string{
			"PATH=" + os.Getenv("PATH"),
			"TMUX=/tmp/nested-tmux,123,0",
		}
	}}

	_, err := runner.Run(context.Background(), "/bin/sh", "-c", `if [ "${TMUX+x}" = x ]; then echo "inherited TMUX=$TMUX"; exit 7; fi`)
	if err != nil {
		t.Fatalf("Run() error = %v, want TMUX stripped", err)
	}
}

func TestShellWelcomeShowsOncePerVersion(t *testing.T) {
	now := time.Date(2026, 5, 10, 12, 34, 56, 0, time.UTC)
	update, _ := testUpdateCommand(t, now)
	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
		update:     update,
	}

	var first bytes.Buffer
	if err := cmd.Run([]string{"--no-install"}, &first, &bytes.Buffer{}); err != nil {
		t.Fatalf("first Run() error = %v", err)
	}
	if !strings.Contains(first.String(), "Welcome to projmux shell "+version.String()) {
		t.Fatalf("first stdout = %q, want welcome", first.String())
	}
	path, err := cmd.welcomeStatePath(version.String())
	if err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), version.String()) {
		t.Fatalf("welcome state = %s, want current version", data)
	}
	var state shellWelcomeState
	if err := json.Unmarshal(data, &state); err != nil {
		t.Fatalf("json.Unmarshal(welcome state) error = %v", err)
	}
	if !state.PendingAttachWelcome {
		t.Fatalf("welcome state = %+v, want pending_attach_welcome=true", state)
	}

	var second bytes.Buffer
	if err := cmd.Run([]string{"--no-install"}, &second, &bytes.Buffer{}); err != nil {
		t.Fatalf("second Run() error = %v", err)
	}
	if strings.Contains(second.String(), "Welcome to projmux shell") {
		t.Fatalf("second stdout = %q, did not expect repeated welcome", second.String())
	}
}

func TestShellWelcomeShowsAfterVersionChange(t *testing.T) {
	home := t.TempDir()
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: (&recordingShellRunner{}).run,
	}
	path, err := cmd.welcomeStatePath(version.String())
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	state := shellWelcomeState{
		Version:             1,
		LastWelcomedVersion: "0.0.1",
		WelcomedAt:          time.Date(2026, 5, 1, 0, 0, 0, 0, time.UTC),
	}
	data, err := json.Marshal(state)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatal(err)
	}

	var stdout bytes.Buffer
	if err := cmd.Run([]string{"--no-install"}, &stdout, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !strings.Contains(stdout.String(), "Welcome to projmux shell "+version.String()) {
		t.Fatalf("stdout = %q, want version-bump welcome", stdout.String())
	}
}

func TestShellWelcomeCorruptStateDoesNotBlockStartup(t *testing.T) {
	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}
	path, err := cmd.welcomeStatePath(version.String())
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte("{not json"), 0o644); err != nil {
		t.Fatal(err)
	}

	var stdout bytes.Buffer
	if err := cmd.Run([]string{"--no-install"}, &stdout, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if strings.Contains(stdout.String(), "Welcome to projmux shell") {
		t.Fatalf("stdout = %q, did not expect welcome with corrupt state", stdout.String())
	}
	if recorder.name != "tmux" {
		t.Fatalf("shell did not continue into tmux, command = %q", recorder.name)
	}
}

func TestShellWelcomeAppliesInlineUpdate(t *testing.T) {
	now := time.Date(2026, 5, 10, 12, 34, 56, 0, time.UTC)
	update, cacheDir := testUpdateCommand(t, now)
	update.getenv = func(name string) string {
		if name == "PROJMUX_INSTALLER" {
			return "npm"
		}
		return ""
	}
	var updateCommands []string
	update.runExternal = func(name string, args []string, stdout, stderr io.Writer) error {
		updateCommands = append(updateCommands, updateApplyCommand{Name: name, Args: args}.String())
		return nil
	}
	latest := testVersionTag(t, 1)
	writeUpdateCacheFixture(t, cacheDir, updateCache{
		Version:     1,
		CheckedAt:   now,
		TagName:     latest,
		PublishedAt: now,
	})

	home := t.TempDir()
	cmd := &shellCommand{
		executable:   func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:    func(string) string { return "" },
		homeDir:      func() (string, error) { return home, nil },
		welcomeInput: strings.NewReader("\n"),
		writeFile:    os.WriteFile,
		runCommand:   (&recordingShellRunner{}).run,
		update:       update,
		updatePromptRunner: shellUpdateRunnerFunc(func(options intpickercompat.Options) (intpickercompat.Result, error) {
			t.Fatalf("unexpected daily update prompt: %#v", options)
			return intpickercompat.Result{}, nil
		}),
		nativePicker: nativePickerFromCompatRunner(shellUpdateRunnerFunc(func(options intpickercompat.Options) (intpickercompat.Result, error) {
			t.Fatalf("unexpected daily update prompt: %#v", options)
			return intpickercompat.Result{}, nil
		})),
	}

	var stdout bytes.Buffer
	if err := cmd.Run([]string{"--no-install"}, &stdout, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	wantCommands := []string{"npm update -g projmux", "projmux tmux apply"}
	if !reflect.DeepEqual(updateCommands, wantCommands) {
		t.Fatalf("update commands = %#v, want %#v", updateCommands, wantCommands)
	}
	if !strings.Contains(stdout.String(), "Update now? [Y/n") {
		t.Fatalf("stdout = %q, want inline prompt", stdout.String())
	}
}

func TestShellWelcomeDeclinePrintsUpdateCommand(t *testing.T) {
	now := time.Date(2026, 5, 10, 12, 34, 56, 0, time.UTC)
	update, cacheDir := testUpdateCommand(t, now)
	update.getenv = func(name string) string {
		if name == "PROJMUX_INSTALLER" {
			return "npm"
		}
		return ""
	}
	update.runExternal = func(name string, args []string, stdout, stderr io.Writer) error {
		t.Fatalf("unexpected update command: %s %#v", name, args)
		return nil
	}
	writeUpdateCacheFixture(t, cacheDir, updateCache{
		Version:     1,
		CheckedAt:   now,
		TagName:     testVersionTag(t, 1),
		PublishedAt: now,
	})

	home := t.TempDir()
	cmd := &shellCommand{
		executable:   func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:    func(string) string { return "" },
		homeDir:      func() (string, error) { return home, nil },
		welcomeInput: strings.NewReader("n\n"),
		writeFile:    os.WriteFile,
		runCommand:   (&recordingShellRunner{}).run,
		update:       update,
		updatePromptRunner: shellUpdateRunnerFunc(func(options intpickercompat.Options) (intpickercompat.Result, error) {
			t.Fatalf("unexpected daily update prompt: %#v", options)
			return intpickercompat.Result{}, nil
		}),
		nativePicker: nativePickerFromCompatRunner(shellUpdateRunnerFunc(func(options intpickercompat.Options) (intpickercompat.Result, error) {
			t.Fatalf("unexpected daily update prompt: %#v", options)
			return intpickercompat.Result{}, nil
		})),
	}

	var stdout bytes.Buffer
	if err := cmd.Run([]string{"--no-install"}, &stdout, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !strings.Contains(stdout.String(), "Run `projmux update apply` to upgrade.") {
		t.Fatalf("stdout = %q, want manual update command", stdout.String())
	}
}

func TestShellWelcomeSkipWritesUpdateSkipState(t *testing.T) {
	now := time.Date(2026, 5, 10, 12, 34, 56, 0, time.UTC)
	update, cacheDir := testUpdateCommand(t, now)
	update.getenv = func(name string) string {
		if name == "PROJMUX_INSTALLER" {
			return "npm"
		}
		return ""
	}
	latest := testVersionTag(t, 1)
	writeUpdateCacheFixture(t, cacheDir, updateCache{
		Version:     1,
		CheckedAt:   now,
		TagName:     latest,
		PublishedAt: now,
	})

	home := t.TempDir()
	cmd := &shellCommand{
		executable:   func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:    func(string) string { return "" },
		homeDir:      func() (string, error) { return home, nil },
		welcomeInput: strings.NewReader("s\n"),
		writeFile:    os.WriteFile,
		runCommand:   (&recordingShellRunner{}).run,
		update:       update,
	}

	var stdout bytes.Buffer
	if err := cmd.Run([]string{"--no-install"}, &stdout, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	skipPath, err := cmd.updateSkipPath()
	if err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(skipPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), latest) {
		t.Fatalf("skip state = %s, want %s", data, latest)
	}
	if !strings.Contains(stdout.String(), "Skipped "+latest) {
		t.Fatalf("stdout = %q, want skip confirmation", stdout.String())
	}
}

func TestShellWelcomeSkipsStaleUpdateRow(t *testing.T) {
	now := time.Date(2026, 5, 10, 12, 34, 56, 0, time.UTC)
	update, cacheDir := testUpdateCommand(t, now)
	update.getenv = func(name string) string {
		if name == "PROJMUX_INSTALLER" {
			return "npm"
		}
		return ""
	}
	writeUpdateCacheFixture(t, cacheDir, updateCache{
		Version:     1,
		CheckedAt:   now.Add(-25 * time.Hour),
		TagName:     testVersionTag(t, 1),
		PublishedAt: now.Add(-25 * time.Hour),
	})

	home := t.TempDir()
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: (&recordingShellRunner{}).run,
		update:     update,
	}

	var stdout bytes.Buffer
	if err := cmd.Run([]string{"--no-install"}, &stdout, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if strings.Contains(stdout.String(), "Update:") {
		t.Fatalf("stdout = %q, did not expect stale update row", stdout.String())
	}
}

func TestShellPromptsForCachedNPMUpdateAndApplies(t *testing.T) {
	now := time.Date(2026, 5, 7, 4, 30, 0, 0, time.UTC)
	update, cacheDir := testUpdateCommand(t, now)
	update.getenv = func(name string) string {
		if name == "PROJMUX_INSTALLER" {
			return "npm"
		}
		return ""
	}
	var updateCommands []string
	update.runExternal = func(name string, args []string, stdout, stderr io.Writer) error {
		updateCommands = append(updateCommands, updateApplyCommand{Name: name, Args: args}.String())
		return nil
	}
	latest := testVersionTag(t, 1)
	writeUpdateCacheFixture(t, cacheDir, updateCache{
		Version:     1,
		CheckedAt:   now,
		TagName:     latest,
		HTMLURL:     "https://github.com/crevissepartners/projmux/releases/tag/" + latest,
		PublishedAt: now,
	})

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	var promptOptions intpickercompat.Options
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
		update:     update,
		updatePromptRunner: shellUpdateRunnerFunc(func(options intpickercompat.Options) (intpickercompat.Result, error) {
			promptOptions = options
			return intpickercompat.Result{Value: shellUpdateApply}, nil
		}),
		nativePicker: nativePickerFromCompatRunner(shellUpdateRunnerFunc(func(options intpickercompat.Options) (intpickercompat.Result, error) {
			promptOptions = options
			return intpickercompat.Result{Value: shellUpdateApply}, nil
		})),
	}
	markShellWelcomed(t, cmd)

	var stdout bytes.Buffer
	if err := cmd.Run(nil, &stdout, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if got, want := promptOptions.UI, "shell-update"; got != want {
		t.Fatalf("prompt UI = %q, want %q", got, want)
	}
	if !strings.Contains(promptOptions.Header, latest) {
		t.Fatalf("prompt header = %q, want latest %s", promptOptions.Header, latest)
	}
	for _, want := range []string{shellUpdateApply, shellUpdateLater, shellUpdateSkip} {
		if !hasEntryValue(promptOptions.Entries, want) {
			t.Fatalf("prompt entries = %#v, want %s", promptOptions.Entries, want)
		}
	}
	wantCommands := []string{"npm update -g projmux", "projmux tmux apply"}
	if !reflect.DeepEqual(updateCommands, wantCommands) {
		t.Fatalf("update commands = %#v, want %#v", updateCommands, wantCommands)
	}
	if recorder.name != "tmux" {
		t.Fatalf("shell did not continue into tmux, command = %q", recorder.name)
	}
	if !strings.Contains(stdout.String(), ">> running: npm update -g projmux") {
		t.Fatalf("stdout = %q, want npm update command", stdout.String())
	}
}

func TestShellUpdatePromptLaterContinuesWithoutApplying(t *testing.T) {
	now := time.Date(2026, 5, 7, 4, 30, 0, 0, time.UTC)
	update, cacheDir := testUpdateCommand(t, now)
	update.getenv = func(name string) string {
		if name == "PROJMUX_INSTALLER" {
			return "npm"
		}
		return ""
	}
	update.runExternal = func(name string, args []string, stdout, stderr io.Writer) error {
		t.Fatalf("unexpected update command: %s %#v", name, args)
		return nil
	}
	writeUpdateCacheFixture(t, cacheDir, updateCache{
		Version:     1,
		CheckedAt:   now,
		TagName:     testVersionTag(t, 1),
		PublishedAt: now,
	})

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
		update:     update,
		updatePromptRunner: shellUpdateRunnerFunc(func(options intpickercompat.Options) (intpickercompat.Result, error) {
			return intpickercompat.Result{Value: shellUpdateLater}, nil
		}),
		nativePicker: nativePickerFromCompatRunner(shellUpdateRunnerFunc(func(options intpickercompat.Options) (intpickercompat.Result, error) {
			return intpickercompat.Result{Value: shellUpdateLater}, nil
		})),
	}
	markShellWelcomed(t, cmd)

	if err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if recorder.name != "tmux" {
		t.Fatalf("shell did not continue into tmux, command = %q", recorder.name)
	}
}

func TestShellUpdatePromptSkipsSelectedVersion(t *testing.T) {
	now := time.Date(2026, 5, 7, 4, 30, 0, 0, time.UTC)
	update, cacheDir := testUpdateCommand(t, now)
	update.getenv = func(name string) string {
		if name == "PROJMUX_INSTALLER" {
			return "npm"
		}
		return ""
	}
	latest := testVersionTag(t, 1)
	writeUpdateCacheFixture(t, cacheDir, updateCache{
		Version:     1,
		CheckedAt:   now,
		TagName:     latest,
		PublishedAt: now,
	})

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	promptCalls := 0
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
		update:     update,
		updatePromptRunner: shellUpdateRunnerFunc(func(options intpickercompat.Options) (intpickercompat.Result, error) {
			promptCalls++
			return intpickercompat.Result{Value: shellUpdateSkip}, nil
		}),
		nativePicker: nativePickerFromCompatRunner(shellUpdateRunnerFunc(func(options intpickercompat.Options) (intpickercompat.Result, error) {
			promptCalls++
			return intpickercompat.Result{Value: shellUpdateSkip}, nil
		})),
	}
	markShellWelcomed(t, cmd)

	if err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("first Run() error = %v", err)
	}
	if promptCalls != 1 {
		t.Fatalf("prompt calls after first run = %d, want 1", promptCalls)
	}
	skipPath, err := cmd.updateSkipPath()
	if err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(skipPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), latest) {
		t.Fatalf("skip state = %s, want %s", data, latest)
	}

	if err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("second Run() error = %v", err)
	}
	if promptCalls != 1 {
		t.Fatalf("prompt calls after skipped run = %d, want 1", promptCalls)
	}
}

func TestShellSkipsPromptWithoutFreshSupportedUpdate(t *testing.T) {
	now := time.Date(2026, 5, 7, 4, 30, 0, 0, time.UTC)
	update, cacheDir := testUpdateCommand(t, now)
	update.getenv = func(name string) string {
		if name == "PROJMUX_INSTALLER" {
			return "source"
		}
		return ""
	}
	writeUpdateCacheFixture(t, cacheDir, updateCache{
		Version:     1,
		CheckedAt:   now,
		TagName:     testVersionTag(t, 1),
		PublishedAt: now,
	})

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
		update:     update,
		updatePromptRunner: shellUpdateRunnerFunc(func(options intpickercompat.Options) (intpickercompat.Result, error) {
			t.Fatalf("unexpected update prompt: %#v", options)
			return intpickercompat.Result{}, nil
		}),
		nativePicker: nativePickerFromCompatRunner(shellUpdateRunnerFunc(func(options intpickercompat.Options) (intpickercompat.Result, error) {
			t.Fatalf("unexpected update prompt: %#v", options)
			return intpickercompat.Result{}, nil
		})),
	}
	markShellWelcomed(t, cmd)

	if err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if recorder.name != "tmux" {
		t.Fatalf("shell did not continue into tmux, command = %q", recorder.name)
	}
}

func TestShellRejectsNestedProjmuxSocket(t *testing.T) {
	t.Setenv("TMUX", "/tmp/tmux-1000/projmux,123,0")

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  os.Getenv,
		homeDir:    func() (string, error) { return home, nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}

	err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{})
	if err == nil {
		t.Fatal("expected nested shell error")
	}
	if !strings.Contains(err.Error(), "cannot run inside") {
		t.Fatalf("error = %v, want nested shell guard", err)
	}
	if recorder.name != "" {
		t.Fatalf("tmux command ran despite nested guard: %s %#v", recorder.name, recorder.args)
	}
	configPath := filepath.Join(home, ".config", "projmux", "tmux.conf")
	if _, err := os.Stat(configPath); !os.IsNotExist(err) {
		t.Fatalf("config was written despite nested guard: %v", err)
	}
}

func TestShellRejectsNestedCustomSocket(t *testing.T) {
	t.Setenv("TMUX", "/tmp/tmux-1000/pmx-dev,123,0")

	cmd := &shellCommand{lookupEnv: os.Getenv}
	err := cmd.Run([]string{"--socket", "pmx-dev"}, &bytes.Buffer{}, &bytes.Buffer{})
	if err == nil {
		t.Fatal("expected nested custom socket error")
	}
	if !strings.Contains(err.Error(), `"pmx-dev"`) {
		t.Fatalf("error = %v, want socket name", err)
	}
}

func TestShellRejectsInvalidUsage(t *testing.T) {
	t.Parallel()

	var stderr bytes.Buffer
	err := (&shellCommand{}).Run([]string{"extra"}, &bytes.Buffer{}, &stderr)
	if err == nil {
		t.Fatal("expected error")
	}
	if !strings.Contains(err.Error(), "shell does not accept positional arguments") {
		t.Fatalf("error = %v", err)
	}
	if !strings.Contains(stderr.String(), "Usage:") {
		t.Fatalf("stderr = %q, want usage", stderr.String())
	}
}

type recordingShellRunner struct {
	env  []string
	name string
	args []string
}

func (r *recordingShellRunner) run(_ context.Context, env []string, name string, args ...string) error {
	r.env = append([]string(nil), env...)
	r.name = name
	r.args = append([]string(nil), args...)
	return nil
}

type scriptedShellTmuxRunner struct {
	outputs map[string][]byte
	errors  map[string]error
	calls   []recordedTmuxCall
	onRun   func(recordedTmuxCall)
}

func (r *scriptedShellTmuxRunner) Run(_ context.Context, name string, args ...string) ([]byte, error) {
	call := recordedTmuxCall{name: name, args: append([]string(nil), args...)}
	r.calls = append(r.calls, call)
	if r.onRun != nil {
		r.onRun(call)
	}
	key := shellTmuxCallKey(name, args...)
	if err, ok := r.errors[key]; ok {
		return nil, err
	}
	if output, ok := r.outputs[key]; ok {
		return output, nil
	}
	return nil, nil
}

func shellTmuxCallKey(name string, args ...string) string {
	return strings.Join(append([]string{name}, args...), "\x00")
}

func saveShellSnapshot(t *testing.T, store sessionstate.Store, sessionName, cwd string) {
	t.Helper()
	saveShellSnapshotSource(t, store, sessionName, cwd, "")
}

func saveShellSnapshotSource(t *testing.T, store sessionstate.Store, sessionName, cwd, source string) {
	t.Helper()
	if err := store.Save(sessionstate.Snapshot{
		Version:    sessionstate.Version,
		Session:    sessionName,
		Source:     source,
		DefaultCWD: cwd,
		SavedAt:    time.Date(2026, 5, 12, 1, 2, 3, 0, time.UTC),
		Windows: []sessionstate.Window{{
			Index:           0,
			Name:            "main",
			Layout:          "layout",
			ActivePaneIndex: 0,
			Panes:           []sessionstate.Pane{{Index: 0, CWD: cwd, Recipe: sessionstate.ShellRecipe()}},
		}},
	}); err != nil {
		t.Fatal(err)
	}
}

type shellUpdateRunnerFunc func(options intpickercompat.Options) (intpickercompat.Result, error)

func (f shellUpdateRunnerFunc) Run(options intpickercompat.Options) (intpickercompat.Result, error) {
	return f(options)
}

func markShellWelcomed(t *testing.T, cmd *shellCommand) {
	t.Helper()
	_, ok := cmd.prepareWelcomeState()
	if !ok {
		t.Fatal("prepareWelcomeState did not write welcome state")
	}
}
